import fs from 'node:fs';import path from 'node:path';import {applyCors,authorize} from './_tuya.js';import {requirePermission} from './_rbac.js';
import {FARM_BLOCK_SECTORS,FARM_CAPACITY,FARM_CLONES} from './_farm-model.js';
const FILE=path.resolve(process.env.F2E_DATA_DIR||'/data','farm-rows.json');
const ALLOWED=FARM_CLONES;
const BLOCKS=Object.fromEntries(Object.entries(FARM_BLOCK_SECTORS).map(([id,sectors])=>[id,{sectors}]));
const CAP=FARM_CAPACITY;
const CLONES_FILE=path.resolve(process.env.F2E_DATA_DIR||'/data','farm-clones.json');
const PLAN_FILE=path.resolve(process.env.F2E_DATA_DIR||'/data','farm-planting.json');
const readJson=(f,d)=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}};
const load=()=>{try{return JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{return{version:'1.0',rows:{}}}};
function save(x){fs.mkdirSync(path.dirname(FILE),{recursive:true});const t=FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2),{mode:0o600});fs.renameSync(t,FILE);fs.chmodSync(FILE,0o600)}
function summary(rows){const byClone={},bySector={},byBlock={};for(const r of Object.values(rows||{})){if(!r?.confirmed)continue;const n=Math.max(0,Math.trunc(Number(r.plants||0)));byClone[r.clone]=(byClone[r.clone]||0)+n;bySector[r.sector]=(bySector[r.sector]||0)+n;byBlock[r.block]=(byBlock[r.block]||0)+n}return{by_clone:byClone,by_sector:bySector,by_block:byBlock,rows_confirmed:Object.values(rows||{}).filter(r=>r?.confirmed).length}}
export default async function handler(req,res){applyCors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(!authorize(req,res))return;const x=load();
 if(req.method==='GET')return res.status(200).json({ok:true,allowed_clones:ALLOWED,rows:x.rows||{},summary:summary(x.rows),physical_control:false});
 if(req.method==='POST'){if(!requirePermission(req,res,'configure'))return;const block=Number(req.body?.block||0),sector=Number(req.body?.sector||0),row=Number(req.body?.row||0),plants=Number(req.body?.plants||0),clone=String(req.body?.clone||'');if(!Number.isInteger(block)||!Number.isInteger(sector)||!BLOCKS[block]||!BLOCKS[block].sectors.includes(sector))return res.status(400).json({ok:false,error:'Talhão/setor inválido.'});if(!Number.isInteger(row)||row<1||row>500)return res.status(400).json({ok:false,error:'Número da rua deve ser inteiro entre 1 e 500.'});if(!ALLOWED.includes(clone))return res.status(400).json({ok:false,error:'Variedade inválida.'});if(!Number.isInteger(plants)||plants<1||plants>500)return res.status(400).json({ok:false,error:'Quantidade de plantas deve ser inteira entre 1 e 500.'});const assignment=readJson(CLONES_FILE,{assignments:{}}).assignments?.[String(sector)];if(assignment?.confirmed&&!assignment.clones.includes(clone))return res.status(409).json({ok:false,error:'Variedade não confirmada para este setor.',sector,clone,assigned_clones:assignment.clones});const key=block+'-'+sector+'-'+row;x.rows=x.rows||{};const previous=Number(x.rows[key]?.plants||0),sectorTotal=Object.values(x.rows).filter(r=>r?.confirmed&&r.sector===sector).reduce((a,r)=>a+Number(r.plants||0),0)-previous+plants;if(sectorTotal>CAP[sector])return res.status(409).json({ok:false,error:'A soma das ruas excederia a capacidade do setor.',sector,capacity:CAP[sector],row_total:sectorTotal});const plan=readJson(PLAN_FILE,{sectors:{}}).sectors?.[String(sector)];if(plan&&sectorTotal>Number(plan.planned||0))return res.status(409).json({ok:false,error:'A soma das ruas excederia o planejamento salvo do setor.',sector,planned:Number(plan.planned||0),row_total:sectorTotal});if(plan&&Number(plan.quantities?.[clone]||0)>0){const cloneTotal=Object.entries(x.rows).filter(([k,r])=>k!==key&&r?.confirmed&&r.sector===sector&&r.clone===clone).reduce((a,[,r])=>a+Number(r.plants||0),0)+plants;if(cloneTotal>Number(plan.quantities[clone]))return res.status(409).json({ok:false,error:'As ruas desta variedade excederiam a quantidade planejada.',sector,clone,planned:Number(plan.quantities[clone]),row_total:cloneTotal})}x.rows[key]={block,sector,row,clone,plants,confirmed:true,updated_at:new Date().toISOString(),updated_by:String(req.authPrincipal?.email||req.authPrincipal?.uid||'usuario').slice(0,120)};save(x);return res.status(201).json({ok:true,row:x.rows[key],summary:summary(x.rows),physical_control:false})}
 return res.status(405).json({ok:false,error:'Método não permitido.'})}
