import fs from 'node:fs/promises';import path from 'node:path';import {authorize,verifyFirebaseIdToken} from './_tuya.js';import {createFirebaseUser,updateFirebaseUser} from './_firebase-admin.js';
const FILE=path.join(process.cwd(),'data','ui-users.json');const MASTER_EMAIL=String(process.env.FAZENDA2E_MASTER_EMAIL||'eliveltonoliveiranbo@gmail.com').trim().toLowerCase();
const ALL=['dashboard','irrigation','emergency','climate','auto4','history','intelligence','devices','settings','health','notifications','support','users'];
const LEVELS=['view','operate','configure','admin'];
async function load(){try{return JSON.parse(await fs.readFile(FILE,'utf8'))}catch{return{users:{}}}}async function save(x){await fs.mkdir(path.dirname(FILE),{recursive:true});await fs.writeFile(FILE,JSON.stringify(x,null,2),{mode:0o600})}
function bearer(req){return String(req.headers?.authorization||'').replace(/^Bearer\s+/i,'').trim()}async function actor(req){const id=String(req.headers?.['x-firebase-id-token']||'').trim();if(!id)return null;try{return await verifyFirebaseIdToken(id)}catch{return null}}
function clean(u){return{uid:u.uid,email:u.email,role:u.role,active:u.active!==false,permissions:u.permissions||[],levels:u.levels||['view'],created_at:u.created_at,updated_at:u.updated_at}}
export default async function handler(req,res){if(!authorize(req,res))return;const me=await actor(req);if(!me)return res.status(401).json({ok:false,error:'Sessão de usuário necessária.'});const db=await load();const email=String(me.email||'').toLowerCase();let profile=db.users[me.uid];
if(email===MASTER_EMAIL){profile={...(profile||{}),uid:me.uid,email:me.email,role:'master',active:true,permissions:ALL,levels:LEVELS};db.users[me.uid]=profile;await save(db)}else if(!profile||profile.active===false)return res.status(403).json({ok:false,error:'Usuário sem acesso ao Fazenda 2E.'});
if(req.method==='GET'&&String(req.query?.scope||'')==='me')return res.json({ok:true,user:clean(profile),master:profile.role==='master'});
if(profile.role!=='master')return res.status(403).json({ok:false,error:'Apenas o usuário master pode gerenciar usuários.'});
if(req.method==='GET')return res.json({ok:true,users:Object.values(db.users).map(clean),permissions:ALL,levels:LEVELS});
if(req.method==='POST'){const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),displayName=String(req.body?.name||'').trim();if(!email||password.length<6)return res.status(400).json({ok:false,error:'Informe e-mail e senha com pelo menos 6 caracteres.'});const created=await createFirebaseUser({email,password,displayName});const now=new Date().toISOString();const u={uid:created.uid,email:created.email,name:displayName,role:'user',active:true,permissions:Array.isArray(req.body?.permissions)?req.body.permissions.filter(x=>ALL.includes(x)):['dashboard','irrigation','climate','history','health'],levels:Array.isArray(req.body?.levels)?req.body.levels.filter(x=>LEVELS.includes(x)):['view'],created_at:now,updated_at:now};db.users[u.uid]=u;await save(db);return res.status(201).json({ok:true,user:clean(u)})}
if(req.method==='PATCH'){const uid=String(req.body?.uid||'');const u=db.users[uid];if(!u)return res.status(404).json({ok:false,error:'Usuário não encontrado.'});if(String(u.email||'').toLowerCase()===MASTER_EMAIL)return res.status(400).json({ok:false,error:'O usuário master principal não pode ser limitado.'});u.active=req.body?.active!==false;u.role=req.body?.role==='master'?'master':'user';u.permissions=Array.isArray(req.body?.permissions)?req.body.permissions.filter(x=>ALL.includes(x)):u.permissions;u.levels=Array.isArray(req.body?.levels)?req.body.levels.filter(x=>LEVELS.includes(x)):u.levels;u.updated_at=new Date().toISOString();await updateFirebaseUser(uid,{disabled:u.active===false,password:req.body?.password||undefined,displayName:req.body?.name}).catch(e=>{throw e});await save(db);return res.json({ok:true,user:clean(u)})}
return res.status(405).json({ok:false,error:'Método não permitido.'})}