import fs from 'node:fs/promises';import path from 'node:path';import {authorize,authPrincipal} from './_tuya.js';import {createFirebaseUser,updateFirebaseUser} from './_firebase-admin.js';
const DATA=process.env.FAZENDA2E_DATA_DIR||path.join(process.cwd(),'data'),FILE=path.join(DATA,'ui-users.json'),AUDIT=path.join(DATA,'access-audit.ndjson');const MASTER_EMAIL=String(process.env.FAZENDA2E_MASTER_EMAIL||'eliveltonoliveiranbo@gmail.com').trim().toLowerCase();
const ALL=['dashboard','farm','irrigation','emergency','climate','auto4','history','intelligence','devices','settings','health','notifications','support','users'];const LEVELS=['view','operate','configure','admin'];
async function load(){try{return JSON.parse(await fs.readFile(FILE,'utf8'))}catch{return{users:{}}}}async function save(x){await fs.mkdir(path.dirname(FILE),{recursive:true});await fs.writeFile(FILE,JSON.stringify(x,null,2),{mode:0o600})}
async function audit(me,action,target,details={}){const row={ts:new Date().toISOString(),actor_uid:me.uid,actor_email:me.email,action,target_uid:target?.uid||'',target_email:target?.email||'',details};await fs.mkdir(DATA,{recursive:true});await fs.appendFile(AUDIT,JSON.stringify(row)+'\n',{mode:0o600})}
function actor(req){return req.authPrincipal||authPrincipal(req)||null}function clean(u){return{uid:u.uid,email:u.email,role:u.role,active:u.active!==false,permissions:u.permissions||[],levels:u.levels||['view'],created_at:u.created_at,updated_at:u.updated_at}}
export default async function handler(req,res){if(!authorize(req,res))return;const me=actor(req);if(!me)return res.status(401).json({ok:false,error:'Sessão de usuário necessária.'});const db=await load();const email=String(me.email||'').toLowerCase();const principal=email===MASTER_EMAIL;let profile=db.users[me.uid];
if(principal){profile={...(profile||{}),uid:me.uid,email:me.email,role:'master',active:true,permissions:ALL,levels:LEVELS};db.users[me.uid]=profile;await save(db)}else if(!profile||profile.active===false)return res.status(403).json({ok:false,error:'Usuário sem acesso ao Fazenda 2E.'});
if(req.method==='GET'&&String(req.query?.scope||'')==='me')return res.json({ok:true,user:clean(profile),master:profile.role==='master',principal_master:principal});
if(profile.role!=='master')return res.status(403).json({ok:false,error:'Apenas o usuário master pode gerenciar usuários.'});
if(req.method==='GET'&&String(req.query?.scope||'')==='audit'){let rows=[];try{rows=(await fs.readFile(AUDIT,'utf8')).trim().split('\n').filter(Boolean).slice(-100).reverse().map(x=>JSON.parse(x))}catch{}return res.json({ok:true,audit:rows})}
if(req.method==='GET')return res.json({ok:true,users:Object.values(db.users).map(clean),permissions:ALL,levels:LEVELS,principal_master:principal});
if(req.method==='POST'){const userEmail=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),displayName=String(req.body?.name||'').trim();if(!userEmail||password.length<6)return res.status(400).json({ok:false,error:'Informe e-mail e senha com pelo menos 6 caracteres.'});if(req.body?.role==='master'&&!principal)return res.status(403).json({ok:false,error:'Somente o master principal pode promover outro usuário a master.'});const created=await createFirebaseUser({email:userEmail,password,displayName});const now=new Date().toISOString();const u={uid:created.uid,email:created.email,name:displayName,role:req.body?.role==='master'?'master':'user',active:true,permissions:Array.isArray(req.body?.permissions)?req.body.permissions.filter(x=>ALL.includes(x)):['dashboard','farm','irrigation','climate','history','health'],levels:Array.isArray(req.body?.levels)?req.body.levels.filter(x=>LEVELS.includes(x)):['view'],created_at:now,updated_at:now};db.users[u.uid]=u;await save(db);await audit(me,'user_created',u,{role:u.role,permissions:u.permissions,levels:u.levels});return res.status(201).json({ok:true,user:clean(u)})}
if(req.method==='PATCH'){const uid=String(req.body?.uid||''),u=db.users[uid];if(!u)return res.status(404).json({ok:false,error:'Usuário não encontrado.'});if(String(u.email||'').toLowerCase()===MASTER_EMAIL)return res.status(400).json({ok:false,error:'O usuário master principal não pode ser limitado.'});const nextRole=req.body?.role==null?u.role:(req.body.role==='master'?'master':'user');if(nextRole!==u.role&&!principal)return res.status(403).json({ok:false,error:'Somente o master principal pode alterar função master.'});const before={role:u.role,active:u.active!==false,permissions:u.permissions||[],levels:u.levels||[]};u.active=req.body?.active!==false;u.role=nextRole;u.permissions=Array.isArray(req.body?.permissions)?req.body.permissions.filter(x=>ALL.includes(x)):u.permissions;u.levels=Array.isArray(req.body?.levels)?req.body.levels.filter(x=>LEVELS.includes(x)):u.levels;u.updated_at=new Date().toISOString();await updateFirebaseUser(uid,{disabled:u.active===false,password:req.body?.password||undefined,displayName:req.body?.name});await save(db);await audit(me,'user_updated',u,{before,after:{role:u.role,active:u.active,permissions:u.permissions,levels:u.levels},password_changed:Boolean(req.body?.password)});return res.json({ok:true,user:clean(u)})}
return res.status(405).json({ok:false,error:'Método não permitido.'})}
