import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>{const base=fs.readFileSync(p,'utf8');if(p!=='irrigacao-react/src/main.tsx')return base;const dir='irrigacao-react/src/modules';const modules=fs.existsSync(dir)?fs.readdirSync(dir).filter(x=>/\.(tsx|ts)$/.test(x)).map(x=>fs.readFileSync(dir+'/'+x,'utf8')).join('\n'):'';return base+'\n'+modules};
test('pulso usa deadline a partir da confirmação física ON do ESP32',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/relayOnAt=Number\(onResult\?\.confirmed_at/);assert.match(s,/expected_off_at:\(relayOnAt\|\|Date\.now\(\)\)\+maxOn\*1000/)});
test('pulso não bloqueia OFF aguardando rede durante countdown',()=>{const s=read('server/continuous/seconds-manager.js');assert.doesNotMatch(s,/void safetyCountdown\(maxOn\)/);const a=s.indexOf('const onDeadline=');const b=s.indexOf("await safeOff(interrupted?'pulse_interrupted':'pulse_deadline')",a);const block=s.slice(a,b);assert.doesNotMatch(block,/await weather\(\)/);assert.doesNotMatch(block,/await active\(\)/)});
test('produção persiste estado operacional em /data',()=>{const env=read('.env.oracle');assert.match(env,/^IRRIGATION_STATE_FILE=\/data\/viveiro-segundos\.json$/m)});
test('frontend mostra alertas reais e VPD arredondado',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Alertas ativos/);assert.match(s,/toFixed\(2\)\+' kPa'/);assert.match(s,/state_updated_at\|\|x\.checked_at/)});
test('previsão soma precipitação das próximas 24h',()=>{const s=read('server/api/weather/forecast.js');assert.match(s,/precipitation24=next24\.reduce/);assert.match(s,/precipitation_24h_mm:Number\(precipitation24\.toFixed\(2\)\)/)});
test('login remove service worker e caches legados',()=>{const m=read('irrigacao-react/src/main.tsx'),sw=read('irrigacao-react/public/sw.js');assert.match(m,/getRegistrations\(\)/);assert.match(m,/caches\.delete/);assert.match(sw,/registration\.unregister\(\)/)});
test('contabilidade não soma latência de confirmação ao tempo irrigado',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/daily_irrigated_seconds:Number\(state\.daily_irrigated_seconds\|\|0\)\+Math\.min\(maxOn,actualPulseSeconds\)/);assert.match(s,/source_of_truth:'pulse_id_events'/)});
test('auditoria de scheduler mede OFF e não penaliza atraso seguro de partida',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/filter\(x=>String\(x\?\.kind\|\|''\)==='off_command'\)\.slice\(-4\)/);assert.match(s,/offSchedulerAvg>1500/)});
test('métricas de precisão descartam amostras antigas após correção do relógio',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/Number\(at\)-10\*60\*1000/);assert.match(s,/precision_samples\)\?state\.precision_samples:\[\]\)\.filter/);assert.match(s,/scheduler_precision_samples\)\?state\.scheduler_precision_samples:\[\]\)\.filter/)});
test('resumo diário antigo não esconde pulsos novos da janela ativa',()=>{const s=read('server/continuous/accounting.js');assert.match(s,/canonicalTs>=newestEventTs/)});
test('reinício durante pulso fecha também a contabilidade ao vivo',()=>{const s=read('server/continuous/seconds-manager.js');const a=s.indexOf('export async function suspendSecondsForRestart');const b=s.indexOf('export async function getSecondsManagerState',a);const block=s.slice(a,b);assert.match(block,/daily_pulses_interrupted:Number\(state\.daily_pulses_interrupted\|\|0\)\+1/);assert.match(block,/daily_irrigated_seconds:Number\(state\.daily_irrigated_seconds\|\|0\)\+Math\.min/)});
test('precisão atual não fica contaminada por pulsos legados com erro extremo',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/precision_samples\)\?state\.precision_samples:\[\]\)\.filter\(row=>Number\(row\?\.at\|\|0\)>=cutoff&&Number\(row\?\.abs_error_ms\|\|0\)<=5000\)/)});
test('interface final traduz estados do controlador para operação no campo',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/phaseLabel/);assert.match(s,/waiting_window:'Fora da janela'/);assert.match(s,/rain_paused:'Pausado por chuva'/)});
test('suporte final não possui botões decorativos sem ação',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/className="supportInfo"/);assert.doesNotMatch(s,/\['Alertas recentes','Central de ajuda','Documentação','Sobre o app'\]\.map\(x=><button/)});
test('início mostra contagem regressiva da próxima mudança sem comandar o relé',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Próxima mudança/);assert.match(s,/setInterval\(\(\)=>setNow\(Date\.now\(\)\),1000\)/);assert.match(s,/expected_next_on_at/)});
test('navegação móvel final expõe página ativa e acessibilidade',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/aria-current=\{s===id\?'page':undefined\}/);assert.match(s,/aria-label=\{t\}/);assert.match(s,/mobileGrip/)});
test('menu Irrigação apresenta estado, contagem, programação e proteções',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/irrigationStatus/);assert.match(s,/ESTADO AGORA/);assert.match(s,/Proteções/);assert.match(s,/Retomada após chuva/);assert.match(s,/PRÓXIMA MUDANÇA/)});
test('imagem de produção não força limiar mmap que infla RSS do Node',()=>{const s=read('smartlife/Dockerfile');assert.doesNotMatch(s,/MALLOC_MMAP_THRESHOLD_/);assert.match(s,/MALLOC_ARENA_MAX=2/)});
test('diagnóstico alerta antes de a memória voltar a travar a VM',()=>{const s=read('server/api/irrigation/diagnostics.js');assert.match(s,/rss>=2048\?'critical'/);assert.match(s,/rss>=768\?'warning'/);assert.match(s,/guidedChecks\.memory/)});
test('Saúde exibe memória real do servidor',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Memória do servidor/);assert.match(s,/process_rss_mb/)});
test('submenus da irrigação são botões funcionais e acessíveis',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/function IrrigationTabs/);assert.match(s,/role="tablist"/);assert.match(s,/onClick=\{\(\)=>setTab\(id\)\}/);for(const x of ['Programação','Automático 4.0','Chuva','Simulador'])assert.match(s,new RegExp(x.replace('.','\\.')))});
test('simulador da irrigação permanece somente consultivo',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Simulação segura/);assert.match(s,/Nenhuma alteração física é enviada pelo simulador/)});
test('programação permite janela e dias da semana',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Início da janela','Fim da janela','Dias da irrigação','startMin','endMin','days_mask'])assert.match(s,new RegExp(x));});
test('API envia programação completa ao controlador',()=>{const s=read('irrigacao-react/src/api.ts');for(const x of ['start_minutes','end_minutes','days_mask'])assert.match(s,new RegExp(x));});
test('controlador permite reprogramação segura de ciclo ativo',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/safeOff\('reprogramming'\)/);assert.match(s,/viveiro_cycle_reprogrammed/);assert.doesNotMatch(s,/if\(state\.enabled\)throw new Error\('O modo em segundos já está ativo/);});
test('Automático 4.0 mostra decisão, ciclo atual, alvo e motivo',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['function AutoFlow','DECISÃO DO SISTEMA','AGORA','PROPOSTO','Limites de segurança ativos','last_reason'])assert.match(s,new RegExp(x));});
test('submenu Chuva mostra sequência operacional e contagem de retomada',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['function RainProtection','Detectar chuva','Bloquear irrigação','Aguardar segurança','Retomar ciclo','rain_last_at','Pode retomar'])assert.match(s,new RegExp(x));});
test('retomada por chuva continua condicionada à janela',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/só volta se o dia e o horário ainda estiverem dentro da programação/i);});
test('Relatórios possuem Hoje 7 dias 30 dias e Eventos',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ["'today'|'week'|'month'|'events'",'Últimos 30 dias','Linha do tempo','TAXA DE CONCLUSÃO'])assert.match(s,new RegExp(x));});
test('Relatórios distinguem iniciados concluídos e interrompidos',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Iniciados','Concluídos','Interrompidos','completed_pulses','interrupted_pulses'])assert.match(s,new RegExp(x));});
test('Relatórios usam history3 e trend30 reais do dashboard',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/d\.history3/);assert.match(s,/reports\.trend30/);assert.match(s,/event_counts/);});
test('Relatórios permitem comparação entre datas reais',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Comparar períodos','CompareMetric','MAIS RECENTE','COMPARADO'])assert.match(s,new RegExp(x));});
test('Relatórios exportam CSV e suportam impressão PDF',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Exportar CSV/);assert.match(s,/text\/csv/);assert.match(s,/window\.print\(\)/);assert.match(s,/Imprimir \/ PDF/);});
test('Análises e IA possui Agora Tendências Qualidade e Simular',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ["'now'|'trend'|'quality'|'sim'",'Recomendações explicadas','Qualidade dos dados','Simulador consultivo'])assert.match(s,new RegExp(x));});
test('IA consultiva não oferece comando físico',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/nunca comandam o relé/);assert.match(s,/Nenhum valor simulado é enviado ao controlador/);});
test('IA mostra anomalias e qualidade das fontes',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Anomalias detectadas','Temporização','Smart Life','Weather2-2'])assert.match(s,new RegExp(x));});
test('Dispositivos possui Status Conexões Servidor e Diagnóstico',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ["'status'|'links'|'server'|'diag'",'Mapa de conexões','Servidor Oracle','Diagnóstico por componente'])assert.match(s,new RegExp(x));});
test('Dispositivos mostra cadeia App Oracle Smart Life EKAZA e Weather2-2',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['App Fazenda 2E','Servidor Oracle','Smart Life','EKAZA','Weather2-2'])assert.match(s,new RegExp(x));});
test('Dispositivos expõe saúde e ocorrências sem alterar controlador',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Ocorrências de saúde/);assert.match(s,/Nenhuma ocorrência ativa/);assert.doesNotMatch(s.slice(s.indexOf('function Devices'),s.indexOf('function Settings')),/api\.post|startViveiro|stopViveiro/);});
test('Configurações possui Geral Acessos Alertas e Avançado',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ["'general'|'access'|'alerts'|'advanced'",'Segurança operacional','Eventos prioritários','Ferramentas avançadas'])assert.match(s,new RegExp(x));});
test('Administração de usuários permanece exclusiva do master',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/master\?<UserAdmin auth=\{auth\}/);assert.match(s,/Somente o usuário master gerencia contas e permissões/);});
test('Configurações informa permissões da sessão e proteções físicas',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Permissões desta sessão/);assert.match(s,/Proteções físicas não são desativadas por esta tela/);});
test('Servidor possui proteção contra crescimento anormal de memória',()=>{const s=read('server/continuous/server.js');assert.match(s,/F2E_MEMORY_RESTART_MB/);assert.match(s,/MEMORY_GUARD/);assert.match(s,/suspendSecondsForRestart/);});
test('Health expõe memória e uptime para diagnóstico',()=>{const s=read('server/continuous/server.js');assert.match(s,/rss_mb/);assert.match(s,/uptime_seconds/);});
test('Histórico do dashboard limita leitura para proteger memória',()=>{const s=read('server/api/viveiro/dashboard.js');assert.match(s,/readRecentHistory\(\{sinceMs:historySince,limit:500\}\)/);const st=read('server/api/irrigation/_store.js');assert.match(st,/HISTORY_MAX_CACHE_ENTRIES=1/);assert.match(st,/Math\.min\(10000/);});
test('Nenhum consumidor operacional solicita dezenas de milhares de eventos',()=>{for(const p of ['server/continuous/seconds-manager.js','server/continuous/autonomy-supervisor.js','server/local/history-mirror.js','server/api/viveiro/_dashboard-cache.js']){const s=read(p);assert.doesNotMatch(s,/readRecentHistory\([^\n]{0,160}limit:(?:12000|20000|60000)/);}});
test('Histórico local não carrega arquivo ilimitado inteiro em memória',()=>{const s=read('server/local/history-store.js');assert.match(s,/LOCAL_HISTORY_MAX_ROWS\|\|2500/);assert.match(s,/LOCAL_HISTORY_LOAD_BYTES/);assert.doesNotMatch(s,/readFile\(HISTORY_FILE,'utf8'\)/);const m=read('server/local/history-mirror.js');assert.doesNotMatch(m,/limit:50000/);});
test('Cache remoto mantém somente uma janela pesada de histórico',()=>{const s=read('server/api/irrigation/_store.js');assert.match(s,/HISTORY_MAX_CACHE_ENTRIES=1/);});
test('Leitores comuns ficam limitados e reconciliação comporta o dia inteiro',()=>{for(const p of ['server/api/viveiro/dashboard.js','server/api/viveiro/_dashboard-cache.js','server/continuous/autonomy-supervisor.js',])assert.doesNotMatch(read(p),/limit:2500/);assert.match(read('server/continuous/seconds-manager.js'),/HISTORY_RECENT_LIMIT=5000/);});
test('Live bus limita replay e payload para não reter objetos grandes',()=>{const s=read('server/continuous/live-bus.js');assert.match(s,/MAX_REPLAY_TYPES=16/);assert.match(s,/MAX_REPLAY_PAYLOAD_BYTES=128\*1024/);});
test('Cache de histórico não troca a janela a cada minuto',()=>{const s=read('server/api/irrigation/_store.js');assert.match(s,/HISTORY_CACHE_BUCKET_MS=5\*60\*1000/);assert.match(s,/const key=String\(safeLimit\)/);assert.doesNotMatch(read('server/continuous/seconds-manager.js'),/limit:2500/);});
test('Espelho local mantém somente histórico operacional necessário em RAM',()=>{const s=read('server/local/history-store.js');assert.match(s,/LOCAL_HISTORY_MAX_ROWS\|\|2500/);assert.match(s,/LOCAL_HISTORY_LOAD_BYTES\|\|3\*1024\*1024/);assert.doesNotMatch(read('server/local/history-mirror.js'),/limit:5000/);});
test('Interface usa canal SSE em tempo real e polling apenas como fallback',()=>{const a=read('irrigacao-react/src/api.ts'),m=read('irrigacao-react/src/main.tsx');assert.match(a,/EventSource\('\/api\/viveiro\/live'\)/);assert.match(m,/subscribeViveiroLive/);assert.match(m,/setInterval\(load,5000\)/);});
test('Dashboard operacional é leve e não recalcula relatório de 30 dias',()=>{const s=read('server/api/viveiro/dashboard.js');assert.match(s,/historySince=now-8\*86400000/);assert.match(s,/limit:500/);assert.doesNotMatch(s,/const reports=buildViveiroReports\(/);assert.match(s,/events:selectedRows\.slice\(-120\)/);});
test('VPD atual é sempre calculado da mesma leitura atual de temperatura e umidade',()=>{const s=read('server/api/viveiro/dashboard.js');assert.match(s,/calculatedCurrentVpd=vaporPressureDeficit\(currentTemp,currentHum\)/);assert.match(s,/temperature:currentClimate\.temperature,humidity:currentClimate\.humidity,vpd:currentClimate\.vpd/);assert.doesNotMatch(s,/currentVpd=Number\(activeSeconds\?\.climate4_vpd/);});
test('Automático 4.0 rebaixa confiança quando contabilidade diverge',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/accountingTrusted=String\(state\.accounting_reconciliation\?\.status\|\|''\)==='ok'/);assert.match(s,/safeTrend=accountingTrusted\?trend:\{\.\.\.trend,confidence:'low'/);assert.match(s,/learning_history_trusted:accountingTrusted/);});
test('Dashboard não usa memória climática legada como alvo atual',()=>{const s=read('server/api/viveiro/dashboard.js');assert.doesNotMatch(s,/target_off_seconds:Number\(climateState\?\.climate4_memory/);assert.match(s,/target_off_seconds:Number\(climateState\?\.last_target_off_seconds/);});
test('Latência Smart Life é identificada como confirmação de nuvem',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/confirmação pela nuvem Smart Life/);assert.match(s,/scheduler_delay_high/);});
test('Reconciliação diária lê histórico suficiente para janela inteira',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/const HISTORY_RECENT_LIMIT=5000/);assert.match(s,/readRecentHistory\(\{[\s\S]*?limit:HISTORY_RECENT_LIMIT/);});
test('Reconciliação usa arquivo local completo e não o espelho truncado/remoto',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/readLocalHistoryFileRange\(\{/);assert.match(read('server/local/history-store.js'),/export async function readLocalHistoryFileRange/);});
test('Contabilidade diária usa pulse_id como fonte canônica após reboot/deploy',()=>{const s=read('server/continuous/seconds-manager.js');assert.match(s,/source_of_truth:'pulse_id_events'/);assert.match(s,/daily_pulses_started:expected\.started/);assert.match(s,/daily_pulses_completed:expected\.completed/);assert.match(s,/daily_pulses_interrupted:expected\.interrupted/);});
test('Inícios sem encerramento são identificados por pulse_id e não por simples subtração',()=>{const s=read('server/continuous/accounting.js');assert.match(s,/const finalPulseIds=new Set/);assert.match(s,/unclosed_starts:unclosedStarts/);});
test('Reconciliação canônica não referencia variáveis legadas mismatch/countsMatch',()=>{const s=read('server/continuous/seconds-manager.js');const a=s.indexOf('async function reconcileDailyAccounting');const b=s.indexOf('\n  async function',a+20);const block=s.slice(a,b>0?b:undefined);assert.doesNotMatch(block,/if\(mismatch|countsMatch/);});
test('Automático 4.0 separa avaliação climática de decisão operacional',()=>{const m=read('server/continuous/seconds-manager.js'),d=read('server/api/viveiro/dashboard.js');assert.match(m,/last_climate_evaluated_at:Date\.now\(\)/);assert.match(m,/last_operational_decision:'outside_schedule'/);assert.match(m,/last_operational_decision_at:Date\.now\(\)/);assert.match(d,/climate_evaluated_at:Number\(/);assert.match(d,/operational_decision_at:Number\(/);});
test('Quality Guardian v2 valida rota pública, bundle, Funnel e autenticação sem hardware',()=>{const s=read('scripts/quality-agent.mjs');assert.match(s,/version:2/);assert.match(s,/publicAppCheck/);assert.match(s,/public-no-legacy-splash/);assert.match(s,/funnel-proxy-8080/);assert.match(s,/auth-route-probe/);assert.match(s,/hardware_actions:false/);assert.doesNotMatch(s,/startViveiro|stopViveiro|safeOn|relay.*on/i);});
test('Quality Guardian v2 diferencia falha, aviso e informação e preserva git',()=>{const s=read('scripts/quality-agent.mjs');assert.match(s,/severity='error'/);assert.match(s,/severity:'warning'/);assert.match(s,/severity:'info'/);assert.match(s,/git-dirty/);assert.match(s,/preservadas, sem autofix/);});
test('rota limpa f2e é produzida sem service worker legado',()=>{const s=read('smartlife/Dockerfile');assert.match(s,/dist\/f2e/);assert.match(s,/rm -f dist\/f2e\/sw\.js dist\/f2e\/manifest\.webmanifest/);});
test('Guardian usa ciclo leve frequente e auditoria profunda periódica',()=>{const a=read('scripts/quality-agent.mjs'),l=read('scripts/quality-agent-loop.sh');assert.match(a,/F2E_QA_FAST/);assert.match(a,/F2E_QA_NOTIFY/);assert.match(l,/F2E_QA_DEEP_EVERY/);assert.match(l,/F2E_QA_FAST=1/);assert.match(l,/F2E_QA_FAST=0/);});
test('Supervisor explica evidências e qualidade dos dados sem controle físico',()=>{const s=read('server/continuous/intelligence-4.2.js');assert.match(s,/version:4.8/);assert.match(s,/explanations/);assert.match(s,/data_quality/);assert.match(s,/physical_control:false/);assert.match(s,/Automático 4.0 continua sendo o único controlador físico/);});
test('Supervisor principal publica versão preditiva 4.5 mantendo salvaguardas',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/version:4.8/);assert.match(s,/local_supervisor_predictive_4_8/);assert.match(s,/Nenhum acionamento físico pelo supervisor/);});
test('Interface mostra Supervisor 4.5 consultivo e chuva agronômica',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Supervisor 4.8 • consultivo/);assert.match(s,/Classificação/);assert.match(s,/Próxima chuva útil/);assert.match(s,/previsão e simulações não acionam o relé/);});
test('aprendizado compara resultado recente com histórico e detecta degradação sem atuar',()=>{const s=read('server/continuous/decision-journal.js');assert.match(s,/buildLearningDiagnostics/);assert.match(s,/forecast_vs_realized/);assert.match(s,/degradation/);assert.match(s,/physical_control:false/);assert.match(s,/advisory_only/);});
test('Supervisor 4.5 incorpora diagnóstico de aprendizado ao estado publicado',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/buildLearningDiagnostics/);assert.match(s,/version:4.8/);assert.match(s,/local_supervisor_predictive_4_8/);assert.match(s,/learning_diagnostics:learningDiagnostics/);});
test('interface 4.5 mostra resultado recente tendência variação e evidências',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Supervisor 4.8 • consultivo','Resultado recente','Tendência aprendizado','Variação','Evidências pendentes'])assert.match(s,new RegExp(x));});
test('autoteste 4.5 cobre falhas isoladas e múltiplas somente em memória',()=>{const s=read('server/continuous/recovery-selftest.js');for(const x of ['weather_loss','firebase_loss','ekaza_loss','controller_mismatch','history_stale','weather_stale','multiple_dependency_loss'])assert.match(s,new RegExp(x));assert.match(s,/simulation_only/);assert.match(s,/physical_actions:false/);assert.match(s,/commands_sent:0/);});
test('Supervisor 4.5 publica autoteste seguro sem ampliar autoridade física',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/version:4.8/);assert.match(s,/local_supervisor_predictive_4_8/);assert.match(s,/recovery_self_test:recoverySelfTest/);assert.match(s,/Nenhum acionamento físico pelo supervisor/);});
test('interface 4.5 mostra cobertura do autoteste e zero comandos',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Supervisor 4.8 • consultivo','Autoteste seguro','Cenários','Comandos enviados'])assert.match(s,new RegExp(x));});
test('central de notificações integra Telegram ao mesmo pipeline de alertas',()=>{const s=read('server/api/irrigation/_notify.js');assert.match(s,/sendTelegramNotification/);assert.match(s,/telegramAssistantConfig/);assert.match(s,/categoryFor/);assert.match(s,/notificationPolicy/);assert.match(s,/telegram,category/);});
test('Telegram operacional usa token persistido ou ambiente e respeita preferências',()=>{const s=read('server/api/irrigation/_telegram.js');assert.match(s,/guardian-telegram-bot-token/);assert.match(s,/guardian-telegram-chat-id/);assert.match(s,/telegram-assistant-config/);assert.match(s,/telegramAssistantConfig/);assert.match(s,/AbortSignal.timeout\(8000\)/);});
test('preferências Telegram cobrem chuva janela retomada anomalias e resumos',()=>{const s=read('server/api/irrigation/_telegram.js');for(const x of ['rain:true','window_start:true','window_end:true','recovery:true','anomalies:true','morning_summary:true','evening_summary:true'])assert.match(s,new RegExp(x));});
test('resumos inteligentes geram pré-irrigação e fechamento sem comando físico',async()=>{const m=await import('../server/continuous/autonomy-supervisor.js?summary='+Date.now());const context={seconds:{on_seconds:30,off_seconds:90,daily_irrigated_seconds:125,daily_pulses_started:3,daily_pulses_completed:2,daily_pulses_interrupted:1},weather:{metrics:{temperature:{value:29.4},humidity:{value:71},rainDetected:false}},forecast:{summary:{precipitation_24h_mm:4.2,max_rain_probability_24h:65}}};const a={status:'healthy',score:96,intelligence_4_2:{next_action:'Manter observação'}};const morning=m.buildNotificationSummary('morning_summary',context,a,Date.parse('2026-09-23T09:35:00Z'));const evening=m.buildNotificationSummary('evening_summary',context,a,Date.parse('2026-09-23T22:35:00Z'));assert.match(morning.title,/Resumo antes da irrigação/);assert.match(morning.body,/Automático 4.0 mantém a autoridade física/);assert.match(evening.title,/Fechamento do dia/);assert.match(evening.body,/Pulsos: 3 iniciados/);assert.match(evening.body,/Tempo irrigado: 2min 5s/);});
test('agendador de resumos respeita preferências janela curta e programação dinâmica',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/summaryScheduleFor/);assert.match(s,/start-30/);assert.match(s,/end\+15/);assert.match(s,/pref\[kind\]===false/);assert.match(s,/c.minutes>minute\+14/);assert.match(s,/summarySent/);});
test('prioridades inteligentes distinguem emergência atenção e informação',async()=>{const m=await import('../server/api/irrigation/_notify.js?priority='+Date.now());assert.equal(m.notificationPriority('critical').label,'EMERGÊNCIA');assert.equal(m.notificationPriority('warning').label,'ATENÇÃO');assert.equal(m.notificationPriority('info').label,'INFORMAÇÃO');assert.equal(m.notificationPriority('critical').bypassCooldown,true);});
test('pipeline agrupa eventos semelhantes e mantém crítico imediato',()=>{const s=read('server/api/irrigation/_notify.js');assert.match(s,/Ocorrências semelhantes agrupadas/);assert.match(s,/effectiveCooldown=priority.bypassCooldown\?Math\.max\(0\.25/);assert.match(s,/group_count:grouped.count/);assert.match(s,/priority.icon\+' '\+priority.label/);});
test('central expõe política da fila de notificações',async()=>{const m=await import('../server/api/irrigation/_notify.js?queue='+Date.now());const q=m.notificationQueueStatus();assert.equal(q.policy.critical,'imediata');assert.match(q.policy.warning,/agrupamento/);assert.match(q.policy.info,/cooldown/);});
test('recuperação correlaciona falha original duração e normalização',async()=>{const m=await import('../server/continuous/autonomy-supervisor.js?recovery='+Date.now());const opened=Date.parse('2026-09-23T12:00:00Z'),closed=opened+125000;const r=m.recoveryMessage({key:'weather',message:'Weather2-2 sem leitura confiável recente.'},opened,closed);assert.match(r.body,/Weather2-2 sem leitura/);assert.match(r.body,/Tempo em falha: 2 min 5 s/);assert.match(r.body,/Normalizado em/);assert.equal(r.duration_ms,125000);assert.match(r.tag,/weather-recovered/);});
test('Supervisor mantém mapa de incidentes ativos e remove somente após recuperação',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/activeIssueAlerts=new Map/);assert.match(s,/opened_at:now/);assert.match(s,/last_seen_at:now/);assert.match(s,/recoveryMessage\(original/);assert.match(s,/activeIssueAlerts.delete\(key\)/);});
test('notificação de recuperação usa rota limpa f2e',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/recovered,url:'\/f2e\/'/);});
test('central de alertas publica incidentes ativos com duração e prioridade',async()=>{const m=await import('../server/continuous/autonomy-supervisor.js?alerts='+Date.now());assert.equal(typeof m.activeAlertSnapshot,'function');const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/active_alerts:activeAlertSnapshot/);assert.match(s,/duration_ms/);assert.match(s,/status:'active'/);});
test('API Telegram entrega central de alertas sem expor segredos',()=>{const s=read('server/api/irrigation/telegram.js');assert.match(s,/alert_center:\{active,resolved,timeline,filters/);assert.match(s,/critical_count/);assert.match(s,/autonomy\/latest/);});
test('tela Notificações possui Central de Alertas com ativos emergências e duração',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Central de Alertas','Ativos','Emergências','Nenhum alerta ativo','Ativo há'])assert.match(s,new RegExp(x));});
test('histórico de alertas resolvidos registra início fim duração e canais',()=>{const s=read('server/continuous/autonomy-supervisor.js');for(const x of ["event:'alert_resolved'","opened_at:","resolved_at:resolvedAt","duration_ms:resolvedRecovered.duration_ms","recovery_delivery","ROOT+'/alert_history/'"])assert.match(s,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('API da central retorna últimos alertas resolvidos ordenados',()=>{const s=read('server/api/irrigation/telegram.js');assert.match(s,/autonomy\/alert_history/);assert.match(s,/status==='resolved'/);assert.match(s,/resolved_at/);assert.match(s,/slice\(0,30\)/);});
test('interface mostra resolvidos duração normalização e canais',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Resolvidos recentemente','Normalizado','canais:','Telegram','Push','WhatsApp'])assert.match(s,new RegExp(x));});
test('simulação completa cobre emergência agrupamento recuperação e histórico sem rede',async()=>{const m=await import('../server/continuous/recovery-selftest.js?notifySim='+Date.now());const now=Date.parse('2026-09-23T12:00:00Z'),r=m.runNotificationSimulation(now);assert.equal(r.ok,true);assert.deepEqual(r.flow,['emergency','grouping','recovery','history']);assert.equal(r.events[0].type,'alert');assert.equal(r.events[1].type,'grouped');assert.equal(r.events[1].count,2);assert.equal(r.events[2].type,'recovery');assert.equal(r.resolved[0].duration_ms,125000);assert.equal(r.network_requests,0);assert.equal(r.messages_sent,0);assert.equal(r.physical_actions,false);assert.equal(r.commands_sent,0);assert.equal(r.interlocks_modified,false);});
test('simulação de notificações é explicitamente somente em memória',()=>{const s=read('server/continuous/recovery-selftest.js');assert.match(s,/runNotificationSimulation/);assert.match(s,/mode:'simulation_only'/);assert.match(s,/network_sent:false/);assert.match(s,/Fluxo completo de notificações simulado somente em memória/);});
test('diagnóstico dos canais cobre Telegram Push e WhatsApp sem controle físico',async()=>{const m=await import('../server/api/irrigation/_notify.js?diag='+Date.now());const d=await m.notificationChannelDiagnostics();assert.equal(d.physical_control,false);for(const k of ['telegram','push','whatsapp'])assert.ok(d.channels[k]);});
test('runtime registra último sucesso e falha por canal sem segredo',()=>{const s=read('server/api/irrigation/_notify.js');assert.match(s,/last_success_at/);assert.match(s,/last_error_at/);assert.match(s,/last_error/);assert.match(s,/subscriptions:pushCount/);});
test('interface exibe diagnóstico dos três canais',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Diagnóstico dos canais','Último envio:','Última falha:','Diagnóstico informativo'])assert.match(s,new RegExp(x));});
test('resumos derivam horários da programação real e respeitam dia selecionado',async()=>{const m=await import('../server/continuous/autonomy-supervisor.js?sched='+Date.now());const mon=Date.parse('2026-09-21T09:00:00Z');const a=m.summaryScheduleFor({start_minutes:360,end_minutes:1080,days_mask:2},mon);assert.equal(a.selected,true);assert.equal(a.morning_minute,330);assert.equal(a.evening_minute,1095);const b=m.summaryScheduleFor({start_minutes:360,end_minutes:1080,days_mask:1},mon);assert.equal(b.selected,false);});
test('resumos usam previsão Weather2-2 24h real',async()=>{const m=await import('../server/continuous/autonomy-supervisor.js?forecastsum='+Date.now());const r=m.buildNotificationSummary('morning_summary',{seconds:{},weather:{},forecast:{summary:{precipitation_24h_mm:12.34,max_rain_probability_24h:78}}},{},Date.parse('2026-09-21T09:00:00Z'));assert.match(r.body,/12\.3 mm/);assert.match(r.body,/78%/);});
test('deduplicação dos resumos persiste no store e não usa force',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/notification_summaries/);assert.match(s,/persisted\[kind\]/);assert.match(s,/storeSet\(ROOT\+'\/notification_summaries\/'/);assert.doesNotMatch(s,/\.\.\.msg,url:'\/f2e\/',cooldownMinutes:20,force:true/);});
test('aprendizado compara alvo previsto com pulso realizado em vez de médias históricas',async()=>{const m=await import('../server/continuous/decision-journal.js?realized='+Date.now());const now=Date.parse('2026-09-23T12:00:00Z');const h=[{ts:now-3600000,type:'viveiro_automatic4_decision',decision:'MANTER',to_off_seconds:90},{ts:now-3590000,type:'viveiro_pulse_complete',off_seconds:96},{ts:now-3580000,type:'viveiro_pulse_complete',off_seconds:96}];const j=m.buildDecisionJournal(h,now);assert.equal(j[0].predicted_off_seconds,90);assert.equal(j[0].realized_off_seconds,96);const d=m.buildLearningDiagnostics(j,now);assert.equal(d.forecast_vs_realized.metric,'off_seconds');assert.equal(d.forecast_vs_realized.predicted_average,90);assert.equal(d.forecast_vs_realized.realized_average,96);assert.equal(d.forecast_vs_realized.mean_absolute_error_seconds,6);assert.equal(d.forecast_vs_realized.evidence,'decision_target_vs_first_completed_pulse');});
test('diagnóstico não chama tendência histórica de previsão realizada',()=>{const s=read('server/continuous/decision-journal.js');assert.doesNotMatch(s,/predicted_outcome:previousAvg/);assert.match(s,/within_tolerance_percent/);assert.match(s,/decision_target_vs_first_completed_pulse/);});
test('política Telegram permite recuperação informativa mesmo com Push info desabilitado',async()=>{const m=await import('../server/api/irrigation/_notify.js?policy='+Date.now());const p=m.notificationPolicy({level:'info',tag:'weather-recovered',alertCfg:{priorities:{info:false},channels:{push:true}},assistant:{enabled:true,recovery:true}});assert.equal(p.push,false);assert.equal(p.telegram,true);assert.equal(p.any,true);});
test('preferência recovery desligada bloqueia Telegram sem consumir canal inexistente',async()=>{const m=await import('../server/api/irrigation/_notify.js?policy2='+Date.now());const p=m.notificationPolicy({level:'info',tag:'weather-recovered',alertCfg:{priorities:{info:false},channels:{push:true}},assistant:{enabled:true,recovery:false}});assert.equal(p.telegram,false);assert.equal(p.any,false);});
test('pipeline decide elegibilidade antes de cooldown e agrupamento',()=>{const s=read('server/api/irrigation/_notify.js'),a=s.indexOf("if(!policy.any)"),b=s.indexOf('cooldownAllowed',a),c=s.indexOf('groupedBody',b);assert.ok(a>0&&b>a&&c>b);});
test('incidentes ativos do Supervisor persistem e são hidratados após reinício lógico',()=>{const s=read('server/continuous/autonomy-supervisor.js');for(const x of ['active_incidents','hydrateActiveIncidents','persistActiveIncidents','incidentsHydrated'])assert.match(s,new RegExp(x));assert.match(s,/previousIssueKeys=new Set\(activeIssueAlerts.keys\(\)\)/);});
test('emergência idêntica possui supressão mínima anti-flood',()=>{const s=read('server/api/irrigation/_notify.js');assert.match(s,/bypassCooldown\?Math\.max\(0\.25/);});
test('Aprendizado 4.6 mede erro e viés por condição climática sem controle físico',async()=>{const m=await import('../server/continuous/decision-journal.js?l46='+Date.now());const rows=[...Array(8)].map((_,i)=>({predicted_off_seconds:90,realized_off_seconds:100+i,vpd:i<3?.7:i<6?1.4:2.3}));const r=m.buildLearning46(rows);assert.equal(r.version,'4.6');assert.equal(r.validated,true);assert.equal(r.physical_control,false);assert.ok(r.by_condition.umido);assert.ok(r.by_condition.normal);assert.ok(r.by_condition.seco);assert.ok(r.mean_absolute_error_seconds>0);});
test('Clima 3.1 distingue chuva observada de chuva apenas prevista',async()=>{const m=await import('../server/continuous/intelligence-4.2.js?c31='+Date.now());const base={seconds:{automatic_controller:'automatic4',automatic_version:4},weather:{checked_at:Date.now(),metrics:{rainDetected:false,vpd:{value:1.2}}},forecast:{ok:true,generated_at:Date.now(),summary:{precipitation_24h_mm:8,max_rain_probability_24h:80}}};const r=m.buildIntelligence42(base);assert.equal(r.version,4.8);assert.equal(r.climate_3_1.agreement,'chuva_prevista_ainda_nao_observada');assert.equal(r.climate_3_1.physical_control,false);});
test('Supervisor publica Aprendizado 4.6 consultivo',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/buildLearning46/);assert.match(s,/learning_4_6:learning46/);});
test('Central de Alertas 2.0 entrega timeline unificada e filtros',()=>{const s=read('server/api/irrigation/telegram.js');assert.match(s,/const timeline=/);assert.match(s,/timeline_status:'active'/);assert.match(s,/timeline_status:'resolved'/);assert.match(s,/filters:\['all','critical','warning','active','resolved'\]/);assert.match(s,/source:'Supervisor'/);});
test('interface Alertas 2.0 mostra linha do tempo origem prioridade duração e estado',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Central de Alertas 2.0','Linha do tempo de alertas','Origem:','ATIVO','RESOLVIDO','duração'])assert.match(s,new RegExp(x));});
test('Interface 6.0 prioriza clima automático e alertas no painel móvel',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['FAZENDA 2E • PAINEL 6.2','homeActions60','Clima','Automático','Alertas','Dados atuais'])assert.match(s,new RegExp(x));});
test('Interface 6.0 identifica Supervisor 4.6 e mantém controle consultivo',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/Supervisor 4.8 • consultivo/);assert.match(s,/Controle físico/);});
test('Interface 6.0 possui layout responsivo específico para ações prioritárias',()=>{const s=read('irrigacao-react/src/styles.css');assert.match(s,/homeActions60/);assert.match(s,/grid-template-columns:repeat\(3,1fr\)/);assert.match(s,/@media\(max-width:370px\)/);});
test('Disaster Recovery 6.0 simula falhas restart e recuperação sem hardware',async()=>{const rmod=await import('../server/continuous/recovery-selftest.js?dr60='+Date.now()),smod=await import('../server/continuous/autonomy-supervisor.js?dr60='+Date.now());const r=rmod.runDisasterRecoverySimulation(smod.evaluateAutonomy,Date.now());assert.equal(r.ok,true);assert.equal(r.mode,'simulation_only');assert.equal(r.persistence_restored,true);assert.equal(r.network_requests,0);assert.equal(r.commands_sent,0);assert.equal(r.physical_actions,false);assert.equal(r.interlocks_modified,false);assert.equal(r.production_restarted,false);for(const x of ['weather2_loss','multiple_dependency_loss','process_restart_restore','dependencies_recovered'])assert.ok(r.timeline.some(e=>e.name===x));});
test('Disaster Recovery 6.0 correlaciona três incidentes na recuperação simulada',async()=>{const rmod=await import('../server/continuous/recovery-selftest.js?drhist='+Date.now()),smod=await import('../server/continuous/autonomy-supervisor.js?drhist='+Date.now());const r=rmod.runDisasterRecoverySimulation(smod.evaluateAutonomy,Date.now());assert.equal(r.resolved.length,3);assert.deepEqual(r.resolved.map(x=>x.key).sort(),['ekaza','firebase','weather']);assert.ok(r.resolved.every(x=>x.duration_ms>0&&x.status==='resolved'));});
test('health check canônico aceita /health e /api/health antes do router',()=>{const s=read('server/continuous/server.js');assert.match(s,/url\.pathname==='\/health'\|\|url\.pathname==='\/api\/health'/);assert.ok(s.indexOf("url.pathname==='/health'")<s.indexOf("url.pathname.startsWith('/api/')"));});

test('raiz canônica redireciona para interface limpa f2e',()=>{const s=read('server/continuous/server.js');assert.match(s,/setHeader\('Location','\/f2e\/'\)/);assert.doesNotMatch(s,/setHeader\('Location','\/irrigacao\/\?v=/);});
test('Interface 6.0 expõe Clima 3.1 com concordância e frescor sem controle físico',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Clima 3.3','Concordância','Weather2-2','Previsão','Camada consultiva'])assert.ok(s.includes(x));});
test('Interface 6.0 expõe Aprendizado 4.6 amostras erro viés e recomendação consultiva',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Aprendizado 4.8 • evidência real','Amostras confirmadas','Erro ON','Erro OFF','recommendation'])assert.match(s,new RegExp(x,'u'));});
test('incidente resolvido usa histórico idempotente antes de remover ativo',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/resolvedHistoryKey/);assert.match(s,/persistResolvedIncident/);assert.match(s,/alert_history\/'\+resolvedHistoryKey/);assert.match(s,/if\(!\(await persistResolvedIncident\(resolved\)\)\)continue;/);});
test('recuperação pendente é persistida e evita reenviar notificação após falha de armazenamento',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/recovery_pending===true/);assert.match(s,/status:'recovery_pending'/);assert.match(s,/if\(!\(await persistActiveIncidents\(\)\)\)continue;/);assert.match(s,/recovery_delivery_raw/);});
test('persistência de incidentes retorna sucesso ou falha em vez de engolir erro',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/async function persistActiveIncidents\(\).*return true.*return false/s);});
test('agrupamento de notificações possui TTL e limite rígido de memória',()=>{const s=read('server/api/irrigation/_notify.js');assert.match(s,/GROUP_TTL_MS=24\*60\*60\*1000/);assert.match(s,/GROUP_MAX=256/);assert.match(s,/function pruneGroups/);assert.match(s,/groups\.size>GROUP_MAX/);});
test('status da fila expõe política de retenção dos agrupamentos',async()=>{const m=await import('../server/api/irrigation/_notify.js?bounded='+Date.now());const x=m.notificationQueueStatus();assert.equal(x.group_ttl_hours,24);assert.equal(x.group_max,256);assert.ok(x.active_groups<=256);});
test('Aprendizado 4.7 aceita apenas medição confirmada e avalia ON e OFF',async()=>{const m=await import('../server/continuous/decision-journal.js?l47='+Date.now());const now=Date.now(),base={at:now-1000,measurement_confirmed:true,predicted_on_seconds:30,realized_on_seconds:31,predicted_off_seconds:90,realized_off_seconds:92,vpd:1.2};const r=m.buildLearning47(Array.from({length:8},(_,i)=>({...base,at:now-1000-i})),now);assert.equal(r.version,'4.7');assert.equal(r.samples,8);assert.equal(r.validated,true);assert.ok(r.on.mae_seconds>=0);assert.ok(r.off.mae_seconds>=0);assert.equal(r.physical_control,false);});
test('Aprendizado 4.7 rejeita amostra sem confirmação real',async()=>{const m=await import('../server/continuous/decision-journal.js?l47reject='+Date.now());const now=Date.now(),r=m.buildLearning47([{at:now-1,measurement_confirmed:false,predicted_on_seconds:30,realized_on_seconds:30,predicted_off_seconds:90,realized_off_seconds:90}],now);assert.equal(r.samples,0);assert.equal(r.rejected_unconfirmed,1);});
test('Clima 3.2 expõe frescor chuva previsão temperatura umidade e VPD sem controle físico',()=>{const s=read('server/continuous/intelligence-4.2.js');for(const x of ['climate_3_2','weather_age_seconds','forecast_age_minutes','forecast_rain_24h_mm','temperature','humidity','vpd','physical_control:false'])assert.match(s,new RegExp(x));});
test('Supervisor 4.7 publica aprendizado 4.7 e saúde consolidada',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/version:4\.8/);assert.match(s,/learning_4_7:learning47/);assert.match(s,/system_health:/);assert.match(s,/local_supervisor_predictive_4_8/);});
test('Disaster Recovery 6.1 simula falha de store e retry sem ação física',async()=>{const r=(await import('../server/continuous/recovery-selftest.js?dr61='+Date.now())).runDisasterRecoverySimulation((x)=>({status:'healthy',issues:[]}),Date.now());assert.equal(r.version,'6.1');assert.equal(r.state_retry_verified,true);assert.equal(r.physical_actions,false);assert.equal(r.commands_sent,0);assert.ok(r.timeline.some(x=>x.name==='store_write_failure'));});
test('Interface expõe Clima 3.2 Aprendizado 4.7 e filtros da Central de Alertas',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['Clima 3.3','Aprendizado 4.8','Amostras confirmadas','Emergências','setAlertFilter','timeline.slice'])assert.match(s,new RegExp(x));});
test('Aprendizado 4.8 mantém somente evidência real e não aplica mudanças automáticas',async()=>{const m=await import('../server/continuous/decision-journal.js?l48='+Date.now()),now=Date.now(),rows=Array.from({length:8},(_,i)=>({at:now-i*1000,measurement_confirmed:true,evidence_ready:true,predicted_on_seconds:30,realized_on_seconds:31,predicted_off_seconds:90,realized_off_seconds:92,vpd:1.3})),r=m.buildLearning48(rows,now);assert.equal(r.version,'4.8');assert.equal(r.samples,8);assert.equal(r.automatic_changes,false);assert.equal(r.physical_control,false);assert.equal(r.review_ready,true);});
test('Clima 3.3 avalia próximas 6h sem ganhar controle físico',async()=>{const m=await import('../server/continuous/intelligence-4.2.js?c33='+Date.now()),now=Date.now(),r=m.buildIntelligence42({seconds:{},weather:{checked_at:now,metrics:{rainDetected:false,vpd:{value:1.2}}},forecast:{ok:true,generated_at:now,summary:{precipitation_24h_mm:5,max_rain_probability_24h:80},hourly:[{precipitation:1.2,precipitation_probability:70},{precipitation:1.1,precipitation_probability:75}]}});assert.equal(r.version,4.8);assert.equal(r.climate_3_3.operational_reading,'chuva_relevante_proximas_6h');assert.equal(r.climate_3_3.physical_control,false);});
test('Supervisor 4.8 publica aprendizado 4.8 mantendo autoridade física fora do supervisor',()=>{const s=read('server/continuous/autonomy-supervisor.js');assert.match(s,/version:4\.8/);assert.match(s,/learning_4_8:learning48/);assert.match(s,/local_supervisor_predictive_4_8/);assert.match(s,/Nenhum acionamento físico pelo supervisor/);});
test('Interface 6.2 expõe Clima 3.3 e Aprendizado 4.8',()=>{const s=read('irrigacao-react/src/main.tsx');for(const x of ['PAINEL 6.2','Clima 3.3','Supervisor 4.8','Aprendizado 4.8'])assert.match(s,new RegExp(x));});
test('Firebase Admin rejeita credenciais conflitantes e preserva diagnóstico OAuth sem expor segredo',()=>{const s=read('server/api/_firebase-admin.js');assert.match(s,/Credencial Firebase Admin inconsistente/);assert.match(s,/Firebase Admin OAuth/);assert.doesNotMatch(s,/console\.log\([^)]*private_key/);});

test('Pacote 7.0 integra Guardian 5 Clima 4 Auto 4.1 shadow e Aprendizado 5 sem ampliar controle físico',()=>{const i=read('server/continuous/intelligence-4.2.js'),a=read('server/continuous/autonomy-supervisor.js'),l=read('server/continuous/decision-journal.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ["version:'4.0'","version:'4.1-shadow'",'physical_control:false','automatic_changes:false'])assert.match(i,new RegExp(x.replace(/[.*+?^$()|[\]{}]/g,'\\$&')));assert.match(a,/version:5\.0/);assert.match(a,/learning_5_0:learning50/);assert.match(l,/buildLearning50/);for(const x of ['PAINEL 7.0','Clima 4.0','Guardian 5.0','Aprendizado 5.0','Notificações inteligentes 3.0'])assert.match(u,new RegExp(x.replace('.', '\\.')))});
test('Guardian 5 permanece sem ações físicas e recuperação é somente comunicação/leitura',()=>{const a=read('server/continuous/autonomy-supervisor.js'),q=read('scripts/quality-agent.mjs');assert.match(a,/Guardian 5\.0 recupera apenas comunicação e leitura/);assert.match(q,/hardware_actions:false/);});
test('Auditoria Master pode ser consultada sem expor senha',()=>{const u=read('server/api/users.js');assert.match(u,/scope\|\|'audit'|scope.*audit/);assert.match(u,/access-audit\.ndjson/);assert.match(u,/password_changed:Boolean/)});

test('Disaster Recovery 7 expõe prontidão sem restaurar estado físico',async()=>{const m=await import('../server/api/irrigation/_backup.js?dr7='+Date.now());assert.equal(typeof m.disasterRecovery7Status,'function');const src=read('server/api/irrigation/_backup.js');for(const x of ["version:'7.0'","mode:'safe-dry-run'",'live_relay_state_restored:false','physical_actions:false','commands_sent:0','interlocks_modified:false'])assert.match(src,new RegExp(x.replace(/[.*+?^$()|[\]{}]/g,'\\$&')))});
test('Interface Master consulta auditoria de acessos',()=>{const a=read('irrigacao-react/src/auth.ts'),u=read('irrigacao-react/src/main.tsx');assert.match(a,/userAudit/);assert.match(a,/scope=audit/);assert.match(u,/AUDITORIA DE ACESSOS/);assert.match(u,/auditRows/)});

test('Painel 7 operacional expõe confiabilidade Guardian Auto 4.1 e próxima ação sem controle físico',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['CONFIABILIDADE','GUARDIAN 5.0','AUTO 4.1 SHADOW','PRÓXIMA AÇÃO INTELIGENTE','Sem controle físico','reliability_score'])assert.match(u,new RegExp(x));assert.match(c,/opsPulse70/);assert.match(c,/nextAction70/)});

test('Automático 4.1 compara candidato em shadow com critérios rígidos e zero comandos',()=>{const i=read('server/continuous/intelligence-4.2.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['candidate_off_seconds','delta_off_seconds','minimum_reliability:82','minimum_samples:8','physical_control:false','automatic_changes:false','commands_sent:0'])assert.ok(i.includes(x));for(const x of ['Automático 4.1 • comparação shadow','CANDIDATO 4.1','Comandos enviados pelo 4.1'])assert.ok(u.includes(x))});

test('Pacote 7.1 integra Clima 4.1 Auto 4.2 simulador Aprendizado 5.1 e Guardian 5.1 sem autoridade física',()=>{const i=read('server/continuous/intelligence-4.2.js'),a=read('server/continuous/autonomy-supervisor.js'),l=read('server/continuous/decision-journal.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ["version:'4.2-simulation'","mode:'simulation_only'",'what_if:whatIf','horizons:{h1,h3,h6,h12,h24}','commands_sent:0'])assert.ok(i.includes(x));for(const x of ['buildLearning51','version:5.1','scenario_learning:true'])assert.ok(l.includes(x));for(const x of ["version:5.1","local_supervisor_guardian_5_1",'daily_report:','operational_timeline:','guardian_5_1:'])assert.ok(a.includes(x));for(const x of ['GUARDIAN 5.1','Clima 4.1','Aprendizado 5.1','Simulador • E se?','forecastStrip71'])assert.ok(u.includes(x))});

test('Painel 8.0 prioriza irrigação clima decisão saúde e navegação essencial',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['IRRIGAÇÃO AGORA','Decisão automática','Sistema saudável','INTELIGÊNCIA EM SEGUNDO PLANO',"['climate','Clima',CloudRain]"])assert.ok(u.includes(x));for(const x of ['irrigationHero8','climateCard8','decisionCard8','systemHealth8','advanced8'])assert.ok(c.includes(x))});

test('Painel 8.1 oferece modo noturno persistente e respeita redução de movimento',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['f2e-theme','dataset.theme','Alternar modo noturno','headerTools81'])assert.ok(u.includes(x));for(const x of [':root[data-theme="dark"]','prefers-reduced-motion','headerTools81'])assert.ok(c.includes(x))});

test('Painel 8.2 melhora navegação por teclado e safe-area mobile',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['aria-label="Abrir clima e previsão"','aria-label="Abrir decisão automática"','tabIndex={0}','onKeyDown'])assert.ok(u.includes(x));for(const x of [':focus-visible','safe-area-inset-bottom','safe-area-inset-top','-webkit-tap-highlight-color'])assert.ok(c.includes(x))});

test('Painel 8.3 expõe clima 24h, timeline e decisão explicável sem controle físico novo',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['OperationalTimeline83','Linha do tempo operacional','h12','h24','source_reliability','ExplainDecision83','Por que o sistema decidiu isso?','não enviam comandos físicos'])assert.ok(u.includes(x));for(const x of ['climateHorizon83','timeline83','explain83','reliability83'])assert.ok(c.includes(x))});

test('Guardian 5.2 e relatório diário inteligente permanecem consultivos',()=>{const s=read('server/continuous/autonomy-supervisor.js'),u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ["version:5.2","local_supervisor_guardian_5_2","guardian_5_2","automatic_hardware_actions:false","version:'1.1'","simulation_candidate_seconds"])assert.ok(s.includes(x));for(const x of ['Guardian 5.2','Relatório diário inteligente','Guardian52','dailySmart52'])assert.ok(u.includes(x));assert.ok(c.includes('.guardian52'))});

test('Aprendizado 5.2 valida Shadow por cenário sem ampliar autoridade física',()=>{const l=read('server/continuous/decision-journal.js'),a=read('server/continuous/autonomy-supervisor.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['buildLearning52',"version:5.2","mode:'shadow_learning'",'scenario_performance','shadow_validation','physical_control:false','automatic_changes:false','commands_sent:0'])assert.ok(l.includes(x));assert.ok(a.includes('learning_5_2:learning52'));for(const x of ['Aprendizado 5.2','Cenários validados','Erro Shadow','Evidência Shadow'])assert.ok(u.includes(x))});

test('Hardening final preserva role ausente e padroniza Quality Guardian 5.2',()=>{const u=read('server/api/users.js'),q=read('scripts/quality-agent.mjs');assert.ok(u.includes("req.body?.role==null?u.role"));assert.ok(q.includes('version:5.2'));assert.ok(q.includes('Quality Guardian 5.2'));assert.ok(q.includes('hardware_actions:false'))});

test('Deploy seguro exige testes e smoke antes e depois da troca',()=>{const s=read('scripts/oracle-deploy.sh');for(const x of ['npm test','frontend-runtime-smoke.mjs','F2E_SMOKE_BASE','candidata falhou no smoke test','Health/smoke final falhou'])assert.ok(s.includes(x));assert.ok(s.includes('REPO_DIR/.env'))});

test('Painel 9.0 consolida central modular sem ampliar controle físico',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['FAZENDA 2E • CENTRAL 9.0','Visão geral da operação da fazenda','FarmHub9','Viveiro, café, talhões e insumos','Manejo 9.3 • histórico por setor','nunca acionam bomba, relé ou irrigação'])assert.ok(u.includes(x));for(const x of ['home9Head','now9','modules9','farmModules9','guardian9'])assert.ok(c.includes(x))});

test('Smoke runtime aceita a Central 9.0 sem depender do rótulo antigo da home',()=>{const s=read('scripts/frontend-runtime-smoke.mjs');assert.ok(s.includes('Guardian 5.2'));assert.ok(s.includes('Aprendizado 5.2'))});

test('Painel 9.1 não cria atalhos falsos para módulos ainda sem backend',()=>{const u=read('irrigacao-react/src/main.tsx');for(const x of ['Manejo 9.3 • histórico por setor','Registrar manejo'])assert.ok(u.includes(x));assert.ok(!u.includes("go('history')}><Sprout/><span><b>Café"))});

test('Café e Talhões 9.1 usam cadastro confirmado e permanecem somente leitura',()=>{const a=read('server/api/farm.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['clones:FARM_CLONES','total_plants','read_only:true','physical_control:false'])assert.ok(a.includes(x));assert.ok(r.includes("'farm':farmApi"));for(const x of ['Manejo 9.3 • histórico por setor','Setores'])assert.ok(u.includes(x))});

test('Talhões 9.2 individualiza setor sem inventar clone mapa ou manejo',()=>{const a=read('server/api/farm.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ["version:'1.2'","clone_assignment:'aguardando_mapa_confirmado'","map_status:'aguardando_geometria_confirmada'","management_history:'sem_lancamentos_confirmados'"])assert.ok(a.includes(x));for(const x of ['Manejo 9.3 • histórico por setor','Nenhum manejo registrado neste setor'])assert.ok(u.includes(x))});

test('Manejo 9.3 registra histórico por setor sem autoridade física',()=>{const a=read('server/api/farm-management.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['adubacao','fertirrigacao','pulverizacao','praga_doenca','observacao',"requirePermission(req,res,'configure')",'physical_control:false'])assert.ok(a.includes(x));assert.ok(r.includes("'farm/management':farmManagementApi"));for(const x of ['Manejo 9.3 • histórico por setor','Registrar manejo','Nenhum manejo registrado neste setor','Fotos são otimizadas no aparelho'])assert.ok(u.includes(x))});

test('Fotos 9.4 usa arquivo real privado e mantém isolamento físico',()=>{const a=read('server/api/farm-attachment.js'),m=read('server/api/farm-management.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['MAX=650*1024',"requirePermission(req,res,'configure')","mode:0o600",'physical_control:false'])assert.ok(a.includes(x));assert.ok(m.includes('attachment:'));assert.ok(r.includes("'farm/attachment':farmAttachmentApi"));for(const x of ['optimizeFarmPhoto94','Adicionar foto real','Fotos são otimizadas no aparelho','managePhoto94'])assert.ok(u.includes(x))});

test('Ficha do Setor 9.5 consolida somente indicadores reais do setor',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['SectorCard95','Ficha do Setor','Clone a definir','MANEJOS','APLICAÇÕES','OCORRÊNCIAS','FOTOS','Dados confirmados','Indicadores de manejo usam somente o histórico real deste setor.'])assert.ok(u.includes(x));for(const x of ['sectorHero95','sectorKpis95','sectorLast95','sectorPhotos95','sectorIntegrity95'])assert.ok(c.includes(x))});

test('Mapa Fazenda 9.6 diferencia esquema operacional de geometria real',()=>{const a=read('server/api/farm.js'),u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ["mode:'operational_schematic'",'georeferenced:false',"kml_status:'aguardando_kml_atual_confirmado'","sector_geometry:'pending'"])assert.ok(a.includes(x));for(const x of ['FarmMap96','Mapa operacional','Esquema operacional — geometria real em validação','KML PENDENTE','não deve ser usado como limite geográfico'])assert.ok(u.includes(x));for(const x of ['farmMap96','mapHead96','mapLegend96'])assert.ok(c.includes(x))});

test('Georreferenciamento 9.7 valida KML antes de promover geometria',()=>{const a=read('server/api/farm-geo.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['parseKml','review_required',"sectors_detected.length===9",'physical_control:false',"requirePermission(req,res,'configure')"])assert.ok(a.includes(x));assert.ok(r.includes("'farm/geo':farmGeoApi"));for(const x of ['Importar KML para validação','O arquivo é analisado antes de substituir','KML VALIDADO','REVISÃO NECESSÁRIA'])assert.ok(u.includes(x))});

test('Mapa geográfico 9.8 renderiza apenas coordenadas de KML validado e preserva fallback',()=>{const a=read('server/api/farm-geo.js'),u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['preview_coordinates','maxPoints=2500','toFixed(7)'])assert.ok(a.includes(x));for(const x of ['GeoPreview98','geo?.validated&&geo?.analysis?.preview_coordinates','Geometria KML validada','VISUALIZAÇÃO REAL','esquema operacional abaixo continua disponível como fallback'])assert.ok(u.includes(x));for(const x of ['geoPreview98','geoPath98','geoBounds98'])assert.ok(c.includes(x))});

test('Menu Fazenda não referencia ícone Upload sem importação',()=>{const u=read('irrigacao-react/src/main.tsx');assert.match(u,/Tractor[\s\S]{0,80}Upload[\s\S]{0,80}lucide-react/);assert.ok(u.includes('<Upload/>'))});

test('Variedades 9.9 exige confirmação manual e aceita apenas clones cadastrados',()=>{const a=read('server/api/farm-clones.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['const ALLOWED=FARM_CLONES',"requirePermission(req,res,'configure')",'confirmed:true','physical_control:false'])assert.ok(a.includes(x));assert.ok(r.includes("'farm/clones':farmClonesApi"));for(const x of ['CloneAssign99','Confirmar variedades deste setor','não distribui clones automaticamente','04 • Eduardo p42'])assert.ok(u.includes(x))});

test('Planejamento 10.0 respeita capacidade confirmada e não distribui clones sozinho',()=>{const a=read('server/api/farm-planting.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ['const CAP=FARM_CAPACITY',"requirePermission(req,res,'configure')",'planned>capacity','physical_control:false'])assert.ok(a.includes(x));assert.ok(r.includes("'farm/planting':farmPlantingApi"));for(const x of ['PlantingPlan100','Planejamento de plantio','Salvar planejamento do setor','nenhuma distribuição foi preenchida automaticamente'])assert.ok(u.includes(x))});

test('Planejamento 10.1 aparece na ficha e mapa sem inventar dados',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['planting={planting}','mapPlan101','sectorPlan101','PLANEJADO','CAPACIDADE','OCUPAÇÃO','Planejamento ainda não lançado.'])assert.ok(u.includes(x));for(const x of ['mapPlan101','sectorPlanBar101','sectorVar101'])assert.ok(c.includes(x))});

test('Planejamento rua por rua 10.2 soma apenas ruas confirmadas',()=>{const a=read('server/api/farm-rows.js'),r=read('api/router.js'),u=read('irrigacao-react/src/main.tsx');for(const x of ["requirePermission(req,res,'configure')",'confirmed:true','by_clone','by_sector','by_block','physical_control:false'])assert.ok(a.includes(x));assert.ok(r.includes("'farm/rows':farmRowsApi"));for(const x of ['RowPlan102','Planejamento rua por rua','Confirmar esta rua','RUAS CONFIRMADAS','Nenhuma sequência de variedades é criada automaticamente'])assert.ok(u.includes(x))});

test('Mapa de ruas 10.3 mostra somente ruas confirmadas e não finge coordenadas',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['RowMap103','Mapa das ruas confirmadas','Nenhuma rua confirmada','somente dados cadastrados','posição horizontal é esquemática','coordenadas GPS só serão usadas'])assert.ok(u.includes(x));for(const x of ['rowMap103','rowBlocks103','rowLegend103','rowMapEmpty103'])assert.ok(c.includes(x))});

test('Visão consolidada 10.4 compara capacidade planejamento e ruas sem tratar ausência como divergência',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['PlantingOverview104','Visão consolidada do plantio','CAPACIDADE TOTAL','RUAS CONFIRMADAS','PLANEJAMENTO PENDENTE','CONFERIDO','Ausência de lançamento é mostrada como pendência'])assert.ok(u.includes(x));for(const x of ['overview104','overviewChecks104','overviewClones104'])assert.ok(c.includes(x))});

test('Fazenda 10.5 organiza módulos em cinco abas sem remover recursos',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ["'overview','Visão geral'","'map','Mapa'","'planting','Plantio'","'management','Manejo'","'sectors','Setores'",'PlantingOverview104','FarmMap96','CloneAssign99','PlantingPlan100','RowPlan102','SectorCard95','Registrar manejo'])assert.ok(u.includes(x));for(const x of ['farmTabs105','grid-template-columns:repeat(5,1fr)','farmTabEmpty105'])assert.ok(c.includes(x))});
test('Fazenda mobile 10.6 melhora toque rolagem e telas estreitas',()=>{const c=read('irrigacao-react/src/styles.css');for(const x of ['Fazenda mobile 10.6','overflow-x:auto','min-height:42px','max-width:360px','pointer:coarse','touch-action:manipulation','safe-area-inset-bottom'])assert.ok(c.includes(x))});

test('Revisão funcional Fazenda 10.7 isola abas do nav global e trata falha de mapa',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ["alert(e?.message||'Não foi possível importar o mapa.')","farmTab==='overview'","farmTab==='map'","farmTab==='planting'","farmTab==='management'","farmTab==='sectors'"])assert.ok(u.includes(x));for(const x of ['Revisão funcional Fazenda 10.7','left:auto!important','bottom:auto!important','transform:none!important','width:100%!important','button.active:after{display:none!important}'])assert.ok(c.includes(x))});

test('Integridade do plantio 10.8 impede divergência entre variedades plano e ruas',()=>{const a=read('server/api/farm-clones.js'),p=read('server/api/farm-planting.js'),r=read('server/api/farm-rows.js');for(const x of ['Não é possível remover variedade já usada','required_clones'])assert.ok(a.includes(x));for(const x of ['Variedade não confirmada para este setor.','O novo planejamento ficaria abaixo das ruas já confirmadas.','Number.isInteger(n)','Variedade não cadastrada no planejamento.'])assert.ok(p.includes(x));for(const x of ['A soma das ruas excederia a capacidade do setor.','A soma das ruas excederia o planejamento salvo do setor.','As ruas desta variedade excederiam a quantidade planejada.','Number.isInteger(plants)','Number.isInteger(row)'])assert.ok(r.includes(x));for(const x of [a,p,r])assert.ok(x.includes('physical_control:false'))});

test('Quality Guardian sinaliza auditoria degradada do viveiro sem acionar hardware',()=>{
  const q=read('scripts/quality-agent.mjs');
  assert.ok(q.includes("'viveiro-runtime-audit'"));
  assert.ok(q.includes('cloud_latency_high|many_interruptions'));
  assert.ok(q.includes("{severity:'warning'}"));
  assert.ok(q.includes('hardware_actions:false'));
});

test('Validador agronômico 10.10 mostra progresso saldo e inconsistências sem alterar dados',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');for(const x of ['AgroValidator1010','Validador agronômico','CAPACIDADE','PLANEJADO','NAS RUAS','SALDO','Variedades ainda não confirmadas.','Validação informativa baseada somente nos cadastros confirmados.'])assert.ok(u.includes(x));for(const x of ['Validador agronômico 10.10','agroGrid1010','agroSummary1010','article.warning','article.pending','article.progress'])assert.ok(c.includes(x))});

test('Guardian 5.2 observa alertas recentes persistidos do Viveiro',()=>{const s=read('scripts/quality-agent.mjs');for(const x of ['viveiro-history-audit','long_pulse_gap','confirmation_stale','cloud_latency_high','many_interruptions'])assert.ok(s.includes(x))});

test('Revisao Geral 11.0 consolida navegacao cabecalho permissoes e mobile',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css'),users=read('server/api/users.js');for(const x of ["section={s}","FAZENDA 2E • LAVOURA","Gestão da fazenda","id==='home'||id==='menu'"])assert.ok(u.includes(x));assert.ok(users.includes("'dashboard','farm','irrigation'"));for(const x of ['Revisão Geral 11.0','repeat(5,minmax(0,1fr))','font-size:16px!important','.farmTabs105{top:88px}'])assert.ok(c.includes(x))});

test('Guardian 5.2 respeita recuperação posterior de alerta persistido',()=>{const s=read('scripts/quality-agent.mjs');assert.ok(s.includes("x.type==='viveiro_audit_recovered'"));assert.ok(s.includes('active.delete(c)'));});

// guardian-weather-offline-regression
test("Quality Guardian inclui Weather2-2 offline na auditoria persistida do Viveiro",()=>{ const q=fs.readFileSync("scripts/quality-agent.mjs","utf8"); assert.match(q,/bad=new Set\(\[[^\]]*weather_offline/); });

test('menu principal nao vaza estilos fixos para submenus internos',()=>{const u=read('irrigacao-react/src/main.tsx'),c=read('irrigacao-react/src/styles.css');assert.ok(u.includes('className="bottomNav" aria-label="Navegação principal"'));assert.ok(c.includes('nav.bottomNav{'));assert.ok(!/(^|})nav\{/.test(c));assert.ok(c.includes('.coffeeSavedProgram nav{display:flex'));assert.ok(c.includes('.farmTabs105{'))});

test('Viveiro possui helpers de horario e dias usados na renderizacao',()=>{const s=read('irrigacao-react/src/main.tsx');assert.match(s,/function minsClock\(/);assert.match(s,/function clockMins\(/);assert.match(s,/function bitCount\(/);assert.match(s,/value=\{minsClock\(startMin\)\}/);assert.match(s,/String\(bitCount\(days\)\)/)});

test('Auditoria geral: Guardian deduplica event_id antes de classificar falhas repetidas',()=>{
 const s=read('server/continuous/seconds-manager.js');
 assert.match(s,/const uniqueHistory=Array\.from\(new Map\(history\.map/);
 assert.match(s,/const recent30=uniqueHistory\.filter/);
 assert.match(s,/const restarts=uniqueHistory\.filter/);
});
test('Auditoria geral: ESP32 usa o estado ativo viveiro-segundos com fallback legado',()=>{
 const s=read('server/api/esp32-controller.js');
 assert.match(s,/VIVEIRO_FILE=path\.join\(ROOT,'viveiro-segundos\.json'\)/);
 assert.match(s,/VIVEIRO_LEGACY_FILE=path\.join\(ROOT,'viveiro-seconds\.json'\)/);
 assert.match(s,/\[VIVEIRO_FILE,VIVEIRO_LEGACY_FILE\]/);
});

test('Precisão R1: os 30 s físicos começam na confirmação ON do ESP32',()=>{
 const s=read('server/continuous/seconds-manager.js');
 assert.match(s,/expected_off_at:\(relayOnAt\|\|Date\.now\(\)\)\+maxOn\*1000/);
 assert.doesNotMatch(s,/expected_off_at:\(relayOnCommandAt\|\|relayOnAt/);
});


test('Guardian não conta start_delay como uma segunda falha física',()=>{
 const s=read('server/continuous/seconds-manager.js');
 assert.match(s,/\['viveiro_error','viveiro_start_failure'\]\.includes/);
 assert.doesNotMatch(s,/\['viveiro_error','viveiro_start_failure','viveiro_start_delay'\]\.includes/);
 assert.match(s,/Falhas independentes de irrigação se repetiram nos últimos 30 minutos/);
});
