import fs from 'node:fs';
import path from 'node:path';
import {applyCors,authorize} from '../_tuya.js';
import {requirePermission} from '../_rbac.js';
const DATA=process.env.FAZENDA2E_DATA_DIR||'/data', CHAT=path.join(DATA,'guardian-telegram-chat-id'), TOKEN=path.join(DATA,'guardian-telegram-bot-token');
const ASSIST=path.join(DATA,'telegram-assistant-config.json');
const prefs={rain:true,window_start:true,window_end:true,recovery:true,anomalies:true,morning_summary:true,evening_summary:true,enabled:true};
function read(p){try{return fs.readFileSync(p,'utf8').trim()}catch{return''}}
function assistant(){try{return{...prefs,...JSON.parse(read(ASSIST)||'{}')}}catch{return{...prefs}}}
function saveJson(p,x){fs.mkdirSync(path.dirname(p),{recursive:true});const t=p+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2),{mode:0o600});fs.renameSync(t,p)}
function chat(){return String(process.env.TELEGRAM_CHAT_ID||read(CHAT)||'').trim()}
function token(){return String(read(TOKEN)||'').trim()}
function saveSecret(p,v){fs.mkdirSync(DATA,{recursive:true});fs.writeFileSync(p,String(v).trim()+'\n',{mode:0o600})}
async function detect(){const tk=token();if(!tk)return{ok:false,reason:'token_missing'};const r=await fetch('https://api.telegram.org/bot'+encodeURIComponent(tk)+'/getUpdates?limit=20&timeout=0',{signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('Telegram HTTP '+r.status);const x=await r.json();const ms=(x.result||[]).map(u=>u.message||u.edited_message||u.channel_post).filter(m=>m?.chat?.id);if(!ms.length)return{ok:false,reason:'no_messages'};const id=String(ms.at(-1).chat.id);saveSecret(CHAT,id);return{ok:true}}
async function send(text){const tk=token(),id=chat();if(!tk||!id)return{ok:false,reason:'not_configured'};const r=await fetch('https://api.telegram.org/bot'+encodeURIComponent(tk)+'/sendMessage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:id,text:String(text).slice(0,4000)}),signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('Telegram HTTP '+r.status);return{ok:true}}
function status(){const id=chat();return{telegram:{bot_token_configured:Boolean(token()),bound:Boolean(id),chat_id_masked:id?('••••'+id.slice(-4)):null},assistant:assistant()}}
export default async function handler(req,res){applyCors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(!authorize(req,res))return;if(req.method==='GET')return res.status(200).json(status());if(req.method!=='POST')return res.status(405).json({ok:false,error:'Método não permitido.'});if(!requirePermission(req,res,'configure'))return;const b=req.body||{};if(b.action==='set_token'){const v=String(b.token||'').trim();if(!/^\d{6,12}:[A-Za-z0-9_-]{20,}$/.test(v))return res.status(400).json({ok:false,error:'Token inválido.'});saveSecret(TOKEN,v);try{fs.rmSync(CHAT,{force:true})}catch{}return res.status(200).json({...status(),ok:true})}if(b.action==='detect_chat'){const r=await detect();return res.status(r.ok?200:404).json({...status(),...r})}if(b.action==='set_chat_id'){const id=String(b.chat_id||'').trim();if(!/^-?\d{5,20}$/.test(id))return res.status(400).json({ok:false,error:'Chat ID inválido.'});fs.mkdirSync(DATA,{recursive:true});fs.writeFileSync(CHAT,id+'\n',{mode:0o600});return res.status(200).json({...status(),ok:true})}if(b.action==='test'){const r=await send('✅ Fazenda 2E\nTelegram vinculado com sucesso. Os relatórios do Quality Guardian poderão ser enviados para este chat.');return res.status(r.ok?200:400).json({...status(),...r})}if(b.action==='guardian_report'){const text=String(b.text||'').trim();if(!text)return res.status(400).json({ok:false,error:'Relatório vazio.'});const r=await send(text);return res.status(r.ok?200:400).json({...status(),...r})}if(b.action==='set_assistant'){saveJson(ASSIST,{...assistant(),...(b.assistant||{})});return res.status(200).json({...status(),ok:true})}return res.status(400).json({ok:false,error:'Ação inválida.'})}
