const CACHE='fazenda2e-viveiro-shell-v15';
const FALLBACK='/irrigacao/';
const SHELL=['/irrigacao/','/irrigacao/app.css','/irrigacao/app.js','/irrigacao/manifest.webmanifest','/irrigacao/icon.svg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>Promise.all(SHELL.map(url=>cache.add(new Request(url,{cache:'reload'})).catch(()=>null)))));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('fazenda2e-')&&key!==CACHE).map(key=>caches.delete(key)))));self.clients.claim();});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.pathname.startsWith('/api/'))return;if(url.origin!==self.location.origin||!url.pathname.startsWith('/irrigacao/'))return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(FALLBACK,response.clone())).catch(()=>null);return response;}).catch(()=>caches.match(FALLBACK)));return;}event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone())).catch(()=>null);return response;}).catch(()=>caches.match(event.request)));});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('push',event=>{let data={};try{data=event.data?event.data.json():{}}catch{data={body:event.data?.text?.()||'Atualização da irrigação.'}}const level=data.level||'info';event.waitUntil(self.registration.showNotification(data.title||'Fazenda 2E',{body:data.body||'Atualização da irrigação.',tag:data.tag||'fazenda2e',renotify:level==='critical',requireInteraction:level==='critical',data:{url:data.url||'/irrigacao/'},icon:'/irrigacao/icon.svg'}))});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=event.notification.data?.url||'/irrigacao/';event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list){if('focus' in client){client.navigate?.(target);return client.focus()}}return self.clients.openWindow?self.clients.openWindow(target):null}))});
